### ISSUE TITLE
:memo: Write DEV.to > How to Visualize Your DuckDb Database with One Command (and Nothing to Install) 

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#1015]
### Description

In the same way you wrote [How to Visualize Your SQLite Database with One Command (and Nothing to Install) ](https://dev.to/sualeh/how-to-visualize-your-sqlite-database-with-one-command-and-nothing-to-install-1f4m), could you use [DuckDb jdbc driver](https://duckdb.org/docs/api/java.html) to write a dedicated DEV.to article called _How to Visualize Your DuckDb Database with One Command (and Nothing to Install) _ ?

- [Java and DuckDB](https://duckdb.org/docs/api/java.html)
- [`jdbc` driver on Maven Central](https://search.maven.org/artifact/org.duckdb/duckdb_jdbc)
- Jdbc Classname : `org.duckdb.DuckDBDriver`
- Get a connection:

```java
ro_prop.setProperty("duckdb.read_only", "true");
Connection conn_ro = DriverManager.getConnection("jdbc:duckdb:/tmp/my_database", ro_prop);
```

### SchemaCrawler Version

latest

### Java Version

current LTS

### Operating System and Version

Docker

### Relational Database System and Version

DuckDb

### JDBC Driver and Version

current

**Comment by adriens** [comment]
[:bird: Tweet](https://twitter.com/rastadidi/status/1621697634502328323)

**Comment by sualeh** [comment]
@adriens - I will distribute the DuckDB driver with SchemaCrawler, but there is no point in writing an article, since the JDBC driver is very underpowered. It is does not support retrieving primary keys, indexes or foreign keys. All you get is tables and columns, and not even the data types. I could enhance the driver with pull requests (I have done this for the SQLite, PostgreSQL and Cassandra JDBC drivers), but this one will need a lot of work.

With the JDBC driver available in the Docker image though, SchemaCrawler will work with DuckDB.

**Comment by adriens** [comment]
>  It is does not support retrieving primary keys, indexes or foreign keys. All you get is tables and columns, and not even the data types.

:sweat: 

> I could enhance the driver with pull requests (I have done this for the SQLite, PostgreSQL and Cassandra JDBC drivers), but this one will need a lot of work.

Why not filling them an issue ? You could show then what can be actually be done vs. what could be done :rocket: :grey_question:
