### ISSUE TITLE
:money_with_wings: Use cache for money (and time) saving :zap: 

### ISSUE THREAD

**Issue by adriens** [schemacrawler/SchemaCrawler#1201]
### Feature Request

I would like to be able to setup a cache from SC so I can:

- Save money while prototyping and exploring a given database
- Get faster answers on already asked questions

Many possibilities : 

- Use a kind of[ GPTCache](https://gptcache.readthedocs.io/en/latest/bootcamp/openai/chat.html) from SC itself (I don't know about the Java binding)
- Load Python bindings in a cloud-native version of Schemacrawler
- target a custom [vllm](https://vllm.readthedocs.io/en/latest/) instance so calls are delegated to the cache (very less impact on SC)
- Make use of [GPTCache](https://github.com/zilliztech/GPTCache) for a sematnic cache (but required Pyhton binding)

[Do you cache your API results?](https://community.openai.com/t/do-you-cache-your-api-results/23875)

### Additional Context

Some bookmarks

- [Do you cache your API results?](https://community.openai.com/t/do-you-cache-your-api-results/23875)

**Comment by sualeh** [comment]
@adriens The value of SchemaCrawler is being able to get fresh information any time you need it. I think that instead of caching the data, users should simply save their command-line options, and reuse them to get fresh data (new tables and columns). SchemaCrawler offers catalog serialization features to make it easier if there is no live connection to the database.

**Comment by adriens** [comment]
[This is the kind of thing I'm talking about](https://twitter.com/helicone_ai/status/1682656385992122368)

![image](https://github.com/schemacrawler/SchemaCrawler/assets/5235127/47a3a857-47de-4091-be78-a05f95fd7d2f)
