### ISSUE TITLE
All Stored Procedures marked as "function" 

### ISSUE THREAD

**Issue by cdelaet** [schemacrawler/SchemaCrawler#1295]
### Description

When listing the routines in a SQL Server database (or its offline copy), all Stored Procedures are marked as "function". All Functions are also marked as "function", so I suppose it's safe to say that all routines are marked as "function". 

### How to Reproduce

```
schemacrawler.sh  \
  --server=offline \
  --database=testinfordat.ser \
  --info-level=minimum \
  --command=list \
  --routines=".*"
```

Output is (truncated):
```
TESTINFORDAT.dbo.SA_NewStudent;1               [function, returns table]
TESTINFORDAT.dbo.SA_NewStudentAfwezigheidGevolg;1  [function, returns table]
TESTINFORDAT.dbo.SA_NewStudentAfwezigheidInschrProgs;1  [function, returns table]
```

The definition of e.g. SA_NewStudent is (truncated):
```
/* Versie: xxx xx xxx xxxx - xxxxx */
/* Laatst gewijzigd door xxxxxx */
CREATE PROCEDURE [dbo].[SA_NewStudent]
@parGebruiker int,
/* snip */ 
@outPersoonID int OUTPUT
AS
BEGIN

BEGIN TRY

DECLARE @IsTopTransaction int

/* snip*/
END CATCH

END
```

The result is identical when connecting directly to the SQL Server database. 

### SchemaCrawler Version

16.20.4

### Java Version

Oracle Corporation Java HotSpot(TM) 64-Bit Server VM 19.0.2+7-44

### Operating System and Version

Mac OS X 14.0

### Relational Database System and Version

SQL Server 2019

### JDBC Driver and Version

com.microsoft.sqlserver.jdbc.SQLServerDriver 12.2

**Comment by sualeh** [comment]
@cdelaet I am not going to be able to fix this one, since the [official Microsoft JDBC driver](https://github.com/microsoft/mssql-jdbc) reports both stored procedures and functions when `getProcedures` or `getFunctions` is called. SchemaCrawler picks functions with the same signature if there are duplicates, and that is why stored procedures are reported as functions. (As a side note, the [`getProcedures`](https://learn.microsoft.com/en-us/sql/connect/jdbc/reference/getprocedures-method-sqlserverdatabasemetadata?view=sql-server-ver16) is not even compliant with the JDBC specification and returns bad values for `PROCEDURE_TYPE`.) Both `getProcedures` or `getFunctions` call [sp_stored_procedures](https://learn.microsoft.com/en-us/sql/relational-databases/system-stored-procedures/sp-stored-procedures-transact-sql) which reports a combined list of stored procedures and functions. Until Microsoft fixes their driver, SchemaCrawler will not be able to report correctly.

I have tried filing issues with the Microsoft team, and they are very resistant to making these types of changes, do I am not going to file an issue with them.
