### ISSUE TITLE
Postgres function column retrieval problem

### ISSUE THREAD

**Issue by nimatrueway** [schemacrawler/SchemaCrawler#227]
Thanks Sualeh, for the very handy & simple-to-use tool !

In postgres-jdbc-driver as can be seen in [PgDatabaseMetaData#2650](https://github.com/pgjdbc/pgjdbc/blob/f3ade07d7758f134fd137db3ebab544f2211e290/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L2650) the method `getFunctionColumns` is completely delegated to `getProcedureColumns`.

Now in SchemaCrawler, for retrieving columns of a function we have the method `createFunctionColumn` in `FunctionColumnRetriever` [here](https://github.com/schemacrawler/SchemaCrawler/blob/3d387f0d859a046d701adb7f10a19eba3da89d47/schemacrawler-api/src/main/java/schemacrawler/crawl/FunctionColumnRetriever.java#L124) which does not work as it tries to get rows by their column names (`FUNCTION_CAT`, `FUNCTION_SCHEM`, `FUNCTION_NAME`) which in postgres-driver will always be (`PROCEDURE_CAT`, `PROCEDURE_SCHEM`, `PROCEDURE_NAME`).

**Describe the solution you'd like**
A simple, less intrusive patch to make this work would be changing this:
```diff
-    final String columnCatalogName = normalizeCatalogName(results
-      .getString("FUNCTION_CAT"));
-    final String schemaName = normalizeSchemaName(results
-      .getString("FUNCTION_SCHEM"));
-    final String functionName = results.getString("FUNCTION_NAME");
+    final String fColumnCatalogName = normalizeCatalogName(results
+      .getString("FUNCTION_CAT"));
+    final String fSchemaName = normalizeSchemaName(results
+      .getString("FUNCTION_SCHEM"));
+    final String fFunctionName = results.getString("FUNCTION_NAME");
+    // postgres-driver fix: it assumes all routines as procedures
+    final String columnCatalogName = fColumnCatalogName != null ? fColumnCatalogName : normalizeCatalogName(results
+      .getString("PROCEDURE_CAT"));
+    final String schemaName = fSchemaName != null ? fSchemaName : normalizeSchemaName(results
+      .getString("PROCEDURE_SCHEM"));
+    final String functionName = fFunctionName != null ? fFunctionName : results.getString("PROCEDURE_NAME");
```

**Describe alternatives you've considered**
Postgres JDBC could be altered in order to make this work, but I assume changing that would be more difficult.

**Comment by sualeh** [comment]
Thanks for a very clear explanation, @nimatrueway  - I will take a look, and work around this issue in SchemaCrawler.

**Comment by sualeh** [comment]
@nimatrueway - I am not going to fix this issue in SchemaCrawler. The workaround is to use v42.1.4 of the PostgreSQL driver. v42.1.4 reports functions as procedures.

Version v42.2.5 of the driver reports functions as procedures as well as functions, so that there is duplication. Also, as you point out, `getFunctionColumns` does not follow JDBC specifications in the column names returned. In addition, other returned data is incorrect, such as [https://github.com/pgjdbc/pgjdbc/blob/f3ade07d7758f134fd137db3ebab544f2211e290/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L1145-L1146](PgDatabaseMetaData.java#L1145-L1146) and [https://github.com/pgjdbc/pgjdbc/blob/f3ade07d7758f134fd137db3ebab544f2211e290/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L1136-L1137](PgDatabaseMetaData.java#L1136-L1137) for example. Please go ahead and submit a patch for the PostgreSQL driver itself.

**Comment by sualeh** [comment]
SchemaCrawler 16.1.2 will be released with pgjdbc (PostgreSQL JDBC driver) version 42.2.6 which fixes this issue.
