### ISSUE TITLE
Support multiple output types in a single invocation

### ISSUE THREAD

**Issue by morl-la** [schemacrawler/SchemaCrawler#232]
**Describe the solution you'd like**
I would like to be able to generate multiple output formats in a single crawl - given all other parameters are common.

Use Case:
I want to generate both an HTML for diff, documentation etc. and a PDF for ERD.

Sample cli usage:
`... -outputformat=html,pdf outputfile=myschema`
would generate 2 files - myschema.html and myschema.pdf

This would improve times by a lot - as only 1 crawl is needed for any n desired output types.

**Describe alternatives you've considered**
Running SchemaCrawler once for each output type (slow)

**Additional context**
n/a

Thanks!

**Comment by sualeh** [comment]
@pyrocks - this is called a "chain" in SchemaCrawler. The easiest way to do this without writing too much code is to script it in JavaScript. Please [download the SchemaCrawler distribution](https://github.com/schemacrawler/SchemaCrawler/releases/), and try out the chain example. Please also look at the Python example, since you can write chains in any scripting language supported by Java.

**Comment by pyrocks** [comment]
Thanks, I'll check.

I would consider however re-opening this and implementing it (on low priority) as:
1. It is useful and intuitive
2. Not everyone is a developer (although I'm sure the example are simple enough).

If I have time I'll try to tackle it myself.

**Comment by sualeh** [comment]
@pyrocks - Mor - any luck with the JavaScript?

**Comment by sualeh** [comment]
@pyrocks - Mor, I have added documentation for the arguments to `chain.addNext`.

I am closing this issue, since it can  be addressed using [SchemaCrawler Shell](https://github.com/schemacrawler/SchemaCrawler-Shell), or by scripting using chain.
