### ISSUE TITLE
Since schemacrawler-16.2.2 lint create with "--output-format=json" text-format 

### ISSUE THREAD

**Issue by ThisGuenter** [schemacrawler/SchemaCrawler#267]
# Issue

Changing schemacrawler-version from 16.2.1 to a higher version, i get instead of json-output  a text-output.

Found that ability to generate JSON as an output format was removed with 16.2.2 - i used it to identify the "linter id"(which is not reported in text-output) - how can i achive this with the new releases ?

-h still shows:
--output-format=<outputFormatValue>
                      Format of the SchemaCrawler output, where
                        <outputformat> is one of:
                        text - For text output (default)
                        html - For HTML5 output
                        json - For JavaScript Object Notation output
                        scdot - For Graphviz DOT output, for schema only

Unchanged command-line:
INFORMATION: Command line: 
--server=oracle
--host=localhost
--port=1521
--database=orcl
--user=XX
--password=XX
--schemas=XX
--info-level=standard
--output-format=json
--log-level=ALL
--config-file=schemacrawler.config.properties
--linter-configs=schemacrawler-linter-configs.xml
--output-file=initial.dump.txt

# Environment

> Specify the
> * version of SchemaCrawler that you are using - 16.2.4
> * version of Java that you are using - 1.8.0_172
> * operating system and version that you are using - Windows 10
> * relational database and version that you are using - ORACLE 12.2.0.1.0
> * JDBC driver and version that you are using - 19.3.0.0

**Comment by sualeh** [comment]
@ThisGuenter - lint output is still possible, but the JSON format has changed. I will need some time to get you details.

**Comment by sualeh** [comment]
@ThisGuenter - I have fixed the issue of generating JSON reports for lint in SchemaCrawler 16.2.6. In this release the JSON format has changed, since the JSON is generated by the Jackson library. You will need to download Jackson separately using the provided scripts. I have created a Katacoda scenario to walk you through this process. Please try out this procedure - [SchemaCrawler - Examples](https://www.katacoda.com/schemacrawler/scenarios/schemacrawler-examples). Thanks.
