### ISSUE TITLE
Change font size and style for schema comments

### ISSUE THREAD

**Issue by hassanxp** [schemacrawler/SchemaCrawler#272]
**Describe the solution you'd like**
It would be very useful to be able to change the font size and style for column comments, so that they are easily distinguished from the column name and type. If the font size can be configured to be smaller, this makes a complex schema easy to read.

**Describe alternatives you've considered**
The only alternative I could find is to comment-out the column comments from the SQLAlchemy code I use to generate the schema. This approach of course cannot work when extracting schemas from permanent databases.

**Additional context**
An [image](https://i.stack.imgur.com/Y5Y4d.jpg) illustrating the problem is shown in the corresponding slack overflow question [here](https://stackoverflow.com/questions/59036995/change-font-style-for-column-comments-in-schemacrawler/59043220#59043220). This is based on the following SQLAlchemy snippet:

<code>
    Base = declarative_base()

    class my_table(Base):
        __tablename__ = 'my_table'

        my_column = Column(Integer, primary_key=True, autoincrement=False, comment='my column comment')

        def __init__(self, my_column):
            self.my_column = my_column
<code>

**Comment by sualeh** [comment]
@hassanxp - the graphs are generated by Graphviz, and in order to be portable across operating systems, I have limited access to fonts that are generally accessible. Question for you: do you want to see the column comments on the chart? (It is quite easy to hide them.)

**Comment by hassanxp** [comment]
If you can tell me how I can hide them that already is useful, as they do clutter the diagram.
However, in the long term, we would like to see the comments on the diagram or in some other document as they provide useful information. If you have any suggestions how to render them in some other document, then that may be an alternative we can use.

**Comment by sualeh** [comment]
To hide the comments, use the `--no-remarks` command-line switch. To get more control of the fonts, generate the graph in `scdot` format, and tweak the text. After that, you can generate the graph using Graphviz yourself.

Since graphs are generated by Graphviz, there is very little control available, since SchemaCrawler needs to make generated graphs look good on all platforms. 

Another idea for you is to use SchemaCrawler's templating feature to generate [DBML](https://www.dbml.org/home/#intro), and view the graph in [dbdiagram.io](https://dbdiagram.io/d/5d5cb582ced98361d6ddc5ab). Notice how the remarks come up as pop-ups. Please see SchemaCrawler's templating examples on [Katacoda](https://www.katacoda.com/schemacrawler). 

If you want a ready solution, please check out the [SchemaCrawler consulting page](https://www.schemacrawler.com/consulting.html).

**Comment by hassanxp** [comment]
Ok, thanks for all the advice. I appreciate my request at the SchemaCrawler level may be difficult to accommodate. I was thinking to work from the `dot` output, but I will look at all your suggestions. I will close this request.
