### ISSUE TITLE
PostgreSQL : getRemarks for more database constructs

### ISSUE THREAD

**Issue by ChristinaCK7** [schemacrawler/SchemaCrawler#524]
# Bug Report
Hi, i'm trying to get comments of all PostgreSQL database constructs (schema, table, column, constraints, etc.)
getRemarks() for Schema, Constraint, Sequence, Indexes returns always empty string.

**Environment**
Specify the
* version of SchemaCrawler : 16.15.10
* version of Java : 14
* relational database and version : PostgreSQL 12
* JDBC driver and version : postgresql 42.1.4

**Comment by sualeh** [comment]
@ChristinaCK7 - I have added support for remarks on table constraints and indexes for all databases that support it, including PostgreSQL. This will be in the next SchemaCrawler release. At this point, I am not going to add support for schema and sequence remarks, since this is not generally supported by databases other than PostgreSQL.

**Comment by sualeh** [comment]
@ChristinaCK7 - please use SchemaCrawler 16.15.11
