### ISSUE TITLE
Python documentation/examples

### ISSUE THREAD

**Issue by jkoplo** [schemacrawler/SchemaCrawler#865]
### Description

I'm working on creating some Mermaid output using Schemacrawler in a Docker container. While the example is great and works well, it's a bit simple.

I'm looking for some documentation on the objects and methods that are available to use in the Python script.

Also as a bug, there are many places on the website that link to 'examples' (https://www.schemacrawler.com/scripting.html) but the link merely points to the github release. The github release does not contain any example code that I can find.

I've been able to suss out that a `catalog` item is passed into the script and I've found some of the structure of that item and it's methods through your mermaid.py example. Is there full documentation somewhere I can reference?

### How to Reproduce

Run python scripts

### SchemaCrawler Version

16.18.2

### Java Version

Eclipse Adoptium OpenJDK 64-Bit Server VM 11.0.16.1+1

### Operating System and Version

Linux 5.10.102.1-microsoft-standard-WSL2 (Docker)

### Relational Database System and Version

MS-SQL 13.00.7016

### JDBC Driver and Version

Microsoft JDBC Driver 11.2 for SQL Server 11.2.1.0

**Comment by sualeh** [comment]
@jkoplo - I will clarify on the website that examples of SchemaCrawler functionality are available with the main distribution zip. 

What you get within the Python scripting environment is a live connection called "connection", and the SchemaCrawler catalog, called "catalog", and "chain", which is a way to execute more than SchemaCrawler command. Since the code is in Java, javadocs are available, but you will have to work out how to use the equivalent in Python, since I do not have docstrings for those. 

The most interesting object for you is probably "catalog", and the [javadocs are linked from the SchemaCrawler website](https://www.schemacrawler.com/apidocs/schemacrawler/schema/Catalog.html).
For the connection, please refer to the [standard Oracle Java documentation](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html), to see how you can execute queries against your database. For "chain", it is best to see the examples provided along with the main SchemaCrawler distribution zip file.

**Comment by jkoplo** [comment]
Ah, I found it. I was downloading the `bin` release and not the `distribution` release. My assumption was that the distribution release was just a zip of the git repo source code.

Referencing the Java docs works for me. I didn't consider that the classes would be the  same as the Java versions, which is a bit obvious in retrospect.

I think the Python environment is being completely provided by Java? It seems to be Python 2.x and doesn't include some packages that are generally pretty standard (ex. `json`) - which limits what you can do in the Python environment.

With all that said, the project is great and I've been able to work around most of environment issues to create some really nice, filtered Mermaid diagrams. So thanks a ton for all your work.

**Comment by sualeh** [comment]
@jkoplo - I am glad that worked for you, and that the javadocs are readable. Python support is via [Jython](https://www.jython.org/) which supports Python 2.7. Once Jython supports a later Python version, SchemaCrawler will also.
